plugins:
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"
  pmd:
    enabled: true
    config:
      rules:
        - "java-basic"
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 7
      tests_patterns:
        - src/test/**